eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  config:
    import: optional:configserver:http://config-service:8888

jwt:
  secret: ${JWT_SECRET:changeit-changeit-changeit-changeit-32b}