spring:
  application:
    name: identity-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:file:./data/identitydb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
      console:
        enabled: true
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: false

  server:
    port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET:changeit-changeit-changeit-changeit-32b}

management:
  endpoints:
    web:
      exposure:
        include: health,info