server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
    instances:
      booking-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      booking-service:
        baseConfig: default